# Generated by Django 5.2.1 on 2026-02-12 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="shipping_address",
            field=models.TextField(
                blank=True,
                help_text="Shipping address used for order confirmation (guest or override).",
                max_length=1000,
                null=True,
                verbose_name="Shipping address",
            ),
        ),
    ]
